
# Settings required by the default template
# The title of your site name 
name: Blog
url: www.blog.com
author: Blog Author
email: email@email.com
employment: Web Developer
github: username
twitter: username

#destination: ~/public/url.com/blog

baseurl: /blog

permalink: :title/

pygments: true
